// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"enc_s_tvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+4,0,"enc_s_tdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+20,0,"enc_s_tkeep",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+22,0,"enc_s_tlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+23,0,"enc_s_tuser",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+24,0,"enc_s_tready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+25,0,"enc_m_tvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+26,0,"enc_m_tdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+42,0,"enc_m_tkeep",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+44,0,"enc_m_tlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+45,0,"enc_m_tuser",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+46,0,"enc_m_tready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"dec_s_tvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+48,0,"dec_s_tdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+64,0,"dec_s_tkeep",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+66,0,"dec_s_tlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+67,0,"dec_s_tuser",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+68,0,"dec_s_tready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+69,0,"dec_m_tvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+70,0,"dec_m_tdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+86,0,"dec_m_tkeep",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+88,0,"dec_m_tlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+89,0,"dec_m_tuser",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+90,0,"dec_m_tready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+91,0,"tb_inject_mode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+92,0,"cfg_local_mac",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declQuad(c+94,0,"cfg_peer_mac",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declBus(c+96,0,"cfg_local_ip",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+97,0,"cfg_peer_ip",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+98,0,"cfg_udp_port",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+99,0,"cfg_mtu",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+100,0,"stat_enc_frames_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+101,0,"stat_enc_oversize",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+102,0,"stat_dec_frames_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+103,0,"stat_dec_bad_cksum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+104,0,"stat_dec_bad_port",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+105,0,"stat_dec_oversize",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("tb_top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+106,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+107,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+108,0,"enc_s_tvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+109,0,"enc_s_tdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+125,0,"enc_s_tkeep",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+127,0,"enc_s_tlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+128,0,"enc_s_tuser",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+129,0,"enc_s_tready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"enc_m_tvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+131,0,"enc_m_tdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+147,0,"enc_m_tkeep",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+149,0,"enc_m_tlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+150,0,"enc_m_tuser",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+151,0,"enc_m_tready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"dec_s_tvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+153,0,"dec_s_tdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+169,0,"dec_s_tkeep",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+171,0,"dec_s_tlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+172,0,"dec_s_tuser",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+173,0,"dec_s_tready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+174,0,"dec_m_tvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+175,0,"dec_m_tdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+191,0,"dec_m_tkeep",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+193,0,"dec_m_tlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+194,0,"dec_m_tuser",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+195,0,"dec_m_tready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+196,0,"tb_inject_mode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+197,0,"cfg_local_mac",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declQuad(c+199,0,"cfg_peer_mac",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declBus(c+201,0,"cfg_local_ip",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,0,"cfg_peer_ip",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,0,"cfg_udp_port",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+204,0,"cfg_mtu",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+205,0,"stat_enc_frames_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+206,0,"stat_enc_oversize",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+207,0,"stat_dec_frames_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+208,0,"stat_dec_bad_cksum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+209,0,"stat_dec_bad_port",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+210,0,"stat_dec_oversize",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+211,0,"enc_out_tvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+212,0,"enc_out_tdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+228,0,"enc_out_tkeep",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+230,0,"enc_out_tlast",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+231,0,"enc_out_tuser_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+232,0,"enc_out_tready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+233,0,"dec_in_tvalid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+234,0,"dec_in_tdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+250,0,"dec_in_tkeep",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+252,0,"dec_in_tlast",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+253,0,"dec_in_tuser_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+254,0,"dec_in_tready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("decap", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+255,0,"s_axis_tvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+256,0,"s_axis_tdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+272,0,"s_axis_tkeep",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+274,0,"s_axis_tlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+275,0,"s_axis_tuser_size",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+276,0,"s_axis_tready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+277,0,"m_axis_tvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+278,0,"m_axis_tdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+294,0,"m_axis_tkeep",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+296,0,"m_axis_tlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+297,0,"m_axis_tuser_size",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+298,0,"m_axis_tready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+299,0,"cfg_local_ip",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+300,0,"cfg_udp_port",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+301,0,"cfg_mtu",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+302,0,"stat_frames_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+303,0,"stat_drops_bad_cksum",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+304,0,"stat_drops_bad_port",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+305,0,"stat_drops_oversize",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+306,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+307,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+308,0,"state",1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declArray(c+309,0,"carry_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 175,0);
    tracep->declBus(c+315,0,"carry_keep",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->declArray(c+316,0,"ip_hdr_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 159,0);
    tracep->declBus(c+321,0,"tuser_size_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+322,0,"vck_sum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 19,0);
    tracep->declBus(c+323,0,"vck_fold",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBit(c+324,0,"cksum_ok",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+325,0,"b14_ver_ihl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declArray(c+326,0,"b14_ip_hdr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 159,0);
    tracep->declBus(c+331,0,"b16_ip_len",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+332,0,"b23_ip_proto",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+333,0,"b34_udp_dport_beat0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+334,0,"out_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+335,0,"can_accept",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+336,0,"fire_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+337,0,"out_tuser_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declArray(c+338,0,"next_carry_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 175,0);
    tracep->declBus(c+344,0,"next_carry_keep",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 21,0);
    tracep->declBit(c+345,0,"need_tail",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("encap", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+346,0,"s_axis_tvalid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+347,0,"s_axis_tdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+363,0,"s_axis_tkeep",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+365,0,"s_axis_tlast",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+366,0,"s_axis_tuser_size",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+367,0,"s_axis_tready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+368,0,"m_axis_tvalid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+369,0,"m_axis_tdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 511,0);
    tracep->declQuad(c+385,0,"m_axis_tkeep",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBit(c+387,0,"m_axis_tlast",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+388,0,"m_axis_tuser_size",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+389,0,"m_axis_tready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+390,0,"cfg_local_mac",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declQuad(c+392,0,"cfg_peer_mac",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 47,0);
    tracep->declBus(c+394,0,"cfg_local_ip",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+395,0,"cfg_peer_ip",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+396,0,"cfg_udp_port",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+397,0,"cfg_mtu",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+398,0,"stat_frames_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+399,0,"stat_oversize_drops",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+400,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+401,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+402,0,"state",2, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+403,0,"ip_id_ctr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+404,0,"ip_len_comb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+405,0,"udp_len_comb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declArray(c+406,0,"carry_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 223,0);
    tracep->declBus(c+413,0,"carry_keep",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 27,0);
    tracep->declBus(c+414,0,"ck_sum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 19,0);
    tracep->declBus(c+415,0,"ck_fold",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBus(c+416,0,"ip_cksum",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declArray(c+417,0,"hdr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 335,0);
    tracep->declBit(c+428,0,"out_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+429,0,"can_accept",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+430,0,"fire_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declArray(c+431,0,"next_carry_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 223,0);
    tracep->declBus(c+438,0,"next_carry_keep",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 27,0);
    tracep->declBit(c+439,0,"need_tail",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    auto &vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.rst_n));
    bufp->fullBit(oldp+3,(vlSelfRef.enc_s_tvalid));
    bufp->fullWData(oldp+4,(vlSelfRef.enc_s_tdata),512);
    bufp->fullQData(oldp+20,(vlSelfRef.enc_s_tkeep),64);
    bufp->fullBit(oldp+22,(vlSelfRef.enc_s_tlast));
    bufp->fullSData(oldp+23,(vlSelfRef.enc_s_tuser),16);
    bufp->fullBit(oldp+24,(vlSelfRef.enc_s_tready));
    bufp->fullBit(oldp+25,(vlSelfRef.enc_m_tvalid));
    bufp->fullWData(oldp+26,(vlSelfRef.enc_m_tdata),512);
    bufp->fullQData(oldp+42,(vlSelfRef.enc_m_tkeep),64);
    bufp->fullBit(oldp+44,(vlSelfRef.enc_m_tlast));
    bufp->fullSData(oldp+45,(vlSelfRef.enc_m_tuser),16);
    bufp->fullBit(oldp+46,(vlSelfRef.enc_m_tready));
    bufp->fullBit(oldp+47,(vlSelfRef.dec_s_tvalid));
    bufp->fullWData(oldp+48,(vlSelfRef.dec_s_tdata),512);
    bufp->fullQData(oldp+64,(vlSelfRef.dec_s_tkeep),64);
    bufp->fullBit(oldp+66,(vlSelfRef.dec_s_tlast));
    bufp->fullSData(oldp+67,(vlSelfRef.dec_s_tuser),16);
    bufp->fullBit(oldp+68,(vlSelfRef.dec_s_tready));
    bufp->fullBit(oldp+69,(vlSelfRef.dec_m_tvalid));
    bufp->fullWData(oldp+70,(vlSelfRef.dec_m_tdata),512);
    bufp->fullQData(oldp+86,(vlSelfRef.dec_m_tkeep),64);
    bufp->fullBit(oldp+88,(vlSelfRef.dec_m_tlast));
    bufp->fullSData(oldp+89,(vlSelfRef.dec_m_tuser),16);
    bufp->fullBit(oldp+90,(vlSelfRef.dec_m_tready));
    bufp->fullBit(oldp+91,(vlSelfRef.tb_inject_mode));
    bufp->fullQData(oldp+92,(vlSelfRef.cfg_local_mac),48);
    bufp->fullQData(oldp+94,(vlSelfRef.cfg_peer_mac),48);
    bufp->fullIData(oldp+96,(vlSelfRef.cfg_local_ip),32);
    bufp->fullIData(oldp+97,(vlSelfRef.cfg_peer_ip),32);
    bufp->fullSData(oldp+98,(vlSelfRef.cfg_udp_port),16);
    bufp->fullSData(oldp+99,(vlSelfRef.cfg_mtu),16);
    bufp->fullIData(oldp+100,(vlSelfRef.stat_enc_frames_out),32);
    bufp->fullIData(oldp+101,(vlSelfRef.stat_enc_oversize),32);
    bufp->fullIData(oldp+102,(vlSelfRef.stat_dec_frames_out),32);
    bufp->fullIData(oldp+103,(vlSelfRef.stat_dec_bad_cksum),32);
    bufp->fullIData(oldp+104,(vlSelfRef.stat_dec_bad_port),32);
    bufp->fullIData(oldp+105,(vlSelfRef.stat_dec_oversize),32);
    bufp->fullBit(oldp+106,(vlSelfRef.tb_top__DOT__clk));
    bufp->fullBit(oldp+107,(vlSelfRef.tb_top__DOT__rst_n));
    bufp->fullBit(oldp+108,(vlSelfRef.tb_top__DOT__enc_s_tvalid));
    bufp->fullWData(oldp+109,(vlSelfRef.tb_top__DOT__enc_s_tdata),512);
    bufp->fullQData(oldp+125,(vlSelfRef.tb_top__DOT__enc_s_tkeep),64);
    bufp->fullBit(oldp+127,(vlSelfRef.tb_top__DOT__enc_s_tlast));
    bufp->fullSData(oldp+128,(vlSelfRef.tb_top__DOT__enc_s_tuser),16);
    bufp->fullBit(oldp+129,(vlSelfRef.tb_top__DOT__enc_s_tready));
    bufp->fullBit(oldp+130,(vlSelfRef.tb_top__DOT__enc_m_tvalid));
    bufp->fullWData(oldp+131,(vlSelfRef.tb_top__DOT__enc_m_tdata),512);
    bufp->fullQData(oldp+147,(vlSelfRef.tb_top__DOT__enc_m_tkeep),64);
    bufp->fullBit(oldp+149,(vlSelfRef.tb_top__DOT__enc_m_tlast));
    bufp->fullSData(oldp+150,(vlSelfRef.tb_top__DOT__enc_m_tuser),16);
    bufp->fullBit(oldp+151,(vlSelfRef.tb_top__DOT__enc_m_tready));
    bufp->fullBit(oldp+152,(vlSelfRef.tb_top__DOT__dec_s_tvalid));
    bufp->fullWData(oldp+153,(vlSelfRef.tb_top__DOT__dec_s_tdata),512);
    bufp->fullQData(oldp+169,(vlSelfRef.tb_top__DOT__dec_s_tkeep),64);
    bufp->fullBit(oldp+171,(vlSelfRef.tb_top__DOT__dec_s_tlast));
    bufp->fullSData(oldp+172,(vlSelfRef.tb_top__DOT__dec_s_tuser),16);
    bufp->fullBit(oldp+173,(vlSelfRef.tb_top__DOT__dec_s_tready));
    bufp->fullBit(oldp+174,(vlSelfRef.tb_top__DOT__dec_m_tvalid));
    bufp->fullWData(oldp+175,(vlSelfRef.tb_top__DOT__dec_m_tdata),512);
    bufp->fullQData(oldp+191,(vlSelfRef.tb_top__DOT__dec_m_tkeep),64);
    bufp->fullBit(oldp+193,(vlSelfRef.tb_top__DOT__dec_m_tlast));
    bufp->fullSData(oldp+194,(vlSelfRef.tb_top__DOT__dec_m_tuser),16);
    bufp->fullBit(oldp+195,(vlSelfRef.tb_top__DOT__dec_m_tready));
    bufp->fullBit(oldp+196,(vlSelfRef.tb_top__DOT__tb_inject_mode));
    bufp->fullQData(oldp+197,(vlSelfRef.tb_top__DOT__cfg_local_mac),48);
    bufp->fullQData(oldp+199,(vlSelfRef.tb_top__DOT__cfg_peer_mac),48);
    bufp->fullIData(oldp+201,(vlSelfRef.tb_top__DOT__cfg_local_ip),32);
    bufp->fullIData(oldp+202,(vlSelfRef.tb_top__DOT__cfg_peer_ip),32);
    bufp->fullSData(oldp+203,(vlSelfRef.tb_top__DOT__cfg_udp_port),16);
    bufp->fullSData(oldp+204,(vlSelfRef.tb_top__DOT__cfg_mtu),16);
    bufp->fullIData(oldp+205,(vlSelfRef.tb_top__DOT__stat_enc_frames_out),32);
    bufp->fullIData(oldp+206,(vlSelfRef.tb_top__DOT__stat_enc_oversize),32);
    bufp->fullIData(oldp+207,(vlSelfRef.tb_top__DOT__stat_dec_frames_out),32);
    bufp->fullIData(oldp+208,(vlSelfRef.tb_top__DOT__stat_dec_bad_cksum),32);
    bufp->fullIData(oldp+209,(vlSelfRef.tb_top__DOT__stat_dec_bad_port),32);
    bufp->fullIData(oldp+210,(vlSelfRef.tb_top__DOT__stat_dec_oversize),32);
    bufp->fullBit(oldp+211,(vlSelfRef.tb_top__DOT__enc_out_tvalid));
    bufp->fullWData(oldp+212,(vlSelfRef.tb_top__DOT__enc_out_tdata),512);
    bufp->fullQData(oldp+228,(vlSelfRef.tb_top__DOT__enc_out_tkeep),64);
    bufp->fullBit(oldp+230,(vlSelfRef.tb_top__DOT__enc_out_tlast));
    bufp->fullSData(oldp+231,(vlSelfRef.tb_top__DOT__enc_out_tuser_size),16);
    bufp->fullBit(oldp+232,(vlSelfRef.tb_top__DOT__enc_out_tready));
    bufp->fullBit(oldp+233,(vlSelfRef.tb_top__DOT__dec_in_tvalid));
    bufp->fullWData(oldp+234,(vlSelfRef.tb_top__DOT__dec_in_tdata),512);
    bufp->fullQData(oldp+250,(vlSelfRef.tb_top__DOT__dec_in_tkeep),64);
    bufp->fullBit(oldp+252,(vlSelfRef.tb_top__DOT__dec_in_tlast));
    bufp->fullSData(oldp+253,(vlSelfRef.tb_top__DOT__dec_in_tuser_size),16);
    bufp->fullBit(oldp+254,(vlSelfRef.tb_top__DOT__dec_in_tready));
    bufp->fullBit(oldp+255,(vlSelfRef.tb_top__DOT__decap__DOT__s_axis_tvalid));
    bufp->fullWData(oldp+256,(vlSelfRef.tb_top__DOT__decap__DOT__s_axis_tdata),512);
    bufp->fullQData(oldp+272,(vlSelfRef.tb_top__DOT__decap__DOT__s_axis_tkeep),64);
    bufp->fullBit(oldp+274,(vlSelfRef.tb_top__DOT__decap__DOT__s_axis_tlast));
    bufp->fullSData(oldp+275,(vlSelfRef.tb_top__DOT__decap__DOT__s_axis_tuser_size),16);
    bufp->fullBit(oldp+276,(vlSelfRef.tb_top__DOT__decap__DOT__s_axis_tready));
    bufp->fullBit(oldp+277,(vlSelfRef.tb_top__DOT__decap__DOT__m_axis_tvalid));
    bufp->fullWData(oldp+278,(vlSelfRef.tb_top__DOT__decap__DOT__m_axis_tdata),512);
    bufp->fullQData(oldp+294,(vlSelfRef.tb_top__DOT__decap__DOT__m_axis_tkeep),64);
    bufp->fullBit(oldp+296,(vlSelfRef.tb_top__DOT__decap__DOT__m_axis_tlast));
    bufp->fullSData(oldp+297,(vlSelfRef.tb_top__DOT__decap__DOT__m_axis_tuser_size),16);
    bufp->fullBit(oldp+298,(vlSelfRef.tb_top__DOT__decap__DOT__m_axis_tready));
    bufp->fullIData(oldp+299,(vlSelfRef.tb_top__DOT__decap__DOT__cfg_local_ip),32);
    bufp->fullSData(oldp+300,(vlSelfRef.tb_top__DOT__decap__DOT__cfg_udp_port),16);
    bufp->fullSData(oldp+301,(vlSelfRef.tb_top__DOT__decap__DOT__cfg_mtu),16);
    bufp->fullIData(oldp+302,(vlSelfRef.tb_top__DOT__decap__DOT__stat_frames_out),32);
    bufp->fullIData(oldp+303,(vlSelfRef.tb_top__DOT__decap__DOT__stat_drops_bad_cksum),32);
    bufp->fullIData(oldp+304,(vlSelfRef.tb_top__DOT__decap__DOT__stat_drops_bad_port),32);
    bufp->fullIData(oldp+305,(vlSelfRef.tb_top__DOT__decap__DOT__stat_drops_oversize),32);
    bufp->fullBit(oldp+306,(vlSelfRef.tb_top__DOT__decap__DOT__clk));
    bufp->fullBit(oldp+307,(vlSelfRef.tb_top__DOT__decap__DOT__rst_n));
    bufp->fullCData(oldp+308,(vlSelfRef.tb_top__DOT__decap__DOT__state),3);
    bufp->fullWData(oldp+309,(vlSelfRef.tb_top__DOT__decap__DOT__carry_data),176);
    bufp->fullIData(oldp+315,(vlSelfRef.tb_top__DOT__decap__DOT__carry_keep),22);
    bufp->fullWData(oldp+316,(vlSelfRef.tb_top__DOT__decap__DOT__ip_hdr_r),160);
    bufp->fullSData(oldp+321,(vlSelfRef.tb_top__DOT__decap__DOT__tuser_size_r),16);
    bufp->fullIData(oldp+322,(vlSelfRef.tb_top__DOT__decap__DOT__vck_sum),20);
    bufp->fullIData(oldp+323,(vlSelfRef.tb_top__DOT__decap__DOT__vck_fold),17);
    bufp->fullBit(oldp+324,(vlSelfRef.tb_top__DOT__decap__DOT__cksum_ok));
    bufp->fullCData(oldp+325,(vlSelfRef.tb_top__DOT__decap__DOT__b14_ver_ihl),8);
    bufp->fullWData(oldp+326,(vlSelfRef.tb_top__DOT__decap__DOT__b14_ip_hdr),160);
    bufp->fullSData(oldp+331,(vlSelfRef.tb_top__DOT__decap__DOT__b16_ip_len),16);
    bufp->fullCData(oldp+332,(vlSelfRef.tb_top__DOT__decap__DOT__b23_ip_proto),8);
    bufp->fullSData(oldp+333,(vlSelfRef.tb_top__DOT__decap__DOT__b34_udp_dport_beat0),16);
    bufp->fullBit(oldp+334,(vlSelfRef.tb_top__DOT__decap__DOT__out_ready));
    bufp->fullBit(oldp+335,(vlSelfRef.tb_top__DOT__decap__DOT__can_accept));
    bufp->fullBit(oldp+336,(vlSelfRef.tb_top__DOT__decap__DOT__fire_in));
    bufp->fullSData(oldp+337,(vlSelfRef.tb_top__DOT__decap__DOT__out_tuser_size),16);
    bufp->fullWData(oldp+338,(vlSelfRef.tb_top__DOT__decap__DOT__next_carry_data),176);
    bufp->fullIData(oldp+344,(vlSelfRef.tb_top__DOT__decap__DOT__next_carry_keep),22);
    bufp->fullBit(oldp+345,(vlSelfRef.tb_top__DOT__decap__DOT__need_tail));
    bufp->fullBit(oldp+346,(vlSelfRef.tb_top__DOT__encap__DOT__s_axis_tvalid));
    bufp->fullWData(oldp+347,(vlSelfRef.tb_top__DOT__encap__DOT__s_axis_tdata),512);
    bufp->fullQData(oldp+363,(vlSelfRef.tb_top__DOT__encap__DOT__s_axis_tkeep),64);
    bufp->fullBit(oldp+365,(vlSelfRef.tb_top__DOT__encap__DOT__s_axis_tlast));
    bufp->fullSData(oldp+366,(vlSelfRef.tb_top__DOT__encap__DOT__s_axis_tuser_size),16);
    bufp->fullBit(oldp+367,(vlSelfRef.tb_top__DOT__encap__DOT__s_axis_tready));
    bufp->fullBit(oldp+368,(vlSelfRef.tb_top__DOT__encap__DOT__m_axis_tvalid));
    bufp->fullWData(oldp+369,(vlSelfRef.tb_top__DOT__encap__DOT__m_axis_tdata),512);
    bufp->fullQData(oldp+385,(vlSelfRef.tb_top__DOT__encap__DOT__m_axis_tkeep),64);
    bufp->fullBit(oldp+387,(vlSelfRef.tb_top__DOT__encap__DOT__m_axis_tlast));
    bufp->fullSData(oldp+388,(vlSelfRef.tb_top__DOT__encap__DOT__m_axis_tuser_size),16);
    bufp->fullBit(oldp+389,(vlSelfRef.tb_top__DOT__encap__DOT__m_axis_tready));
    bufp->fullQData(oldp+390,(vlSelfRef.tb_top__DOT__encap__DOT__cfg_local_mac),48);
    bufp->fullQData(oldp+392,(vlSelfRef.tb_top__DOT__encap__DOT__cfg_peer_mac),48);
    bufp->fullIData(oldp+394,(vlSelfRef.tb_top__DOT__encap__DOT__cfg_local_ip),32);
    bufp->fullIData(oldp+395,(vlSelfRef.tb_top__DOT__encap__DOT__cfg_peer_ip),32);
    bufp->fullSData(oldp+396,(vlSelfRef.tb_top__DOT__encap__DOT__cfg_udp_port),16);
    bufp->fullSData(oldp+397,(vlSelfRef.tb_top__DOT__encap__DOT__cfg_mtu),16);
    bufp->fullIData(oldp+398,(vlSelfRef.tb_top__DOT__encap__DOT__stat_frames_out),32);
    bufp->fullIData(oldp+399,(vlSelfRef.tb_top__DOT__encap__DOT__stat_oversize_drops),32);
    bufp->fullBit(oldp+400,(vlSelfRef.tb_top__DOT__encap__DOT__clk));
    bufp->fullBit(oldp+401,(vlSelfRef.tb_top__DOT__encap__DOT__rst_n));
    bufp->fullCData(oldp+402,(vlSelfRef.tb_top__DOT__encap__DOT__state),2);
    bufp->fullSData(oldp+403,(vlSelfRef.tb_top__DOT__encap__DOT__ip_id_ctr),16);
    bufp->fullSData(oldp+404,(vlSelfRef.tb_top__DOT__encap__DOT__ip_len_comb),16);
    bufp->fullSData(oldp+405,(vlSelfRef.tb_top__DOT__encap__DOT__udp_len_comb),16);
    bufp->fullWData(oldp+406,(vlSelfRef.tb_top__DOT__encap__DOT__carry_data),224);
    bufp->fullIData(oldp+413,(vlSelfRef.tb_top__DOT__encap__DOT__carry_keep),28);
    bufp->fullIData(oldp+414,(vlSelfRef.tb_top__DOT__encap__DOT__ck_sum),20);
    bufp->fullIData(oldp+415,(vlSelfRef.tb_top__DOT__encap__DOT__ck_fold),17);
    bufp->fullSData(oldp+416,(vlSelfRef.tb_top__DOT__encap__DOT__ip_cksum),16);
    bufp->fullWData(oldp+417,(vlSelfRef.tb_top__DOT__encap__DOT__hdr),336);
    bufp->fullBit(oldp+428,(vlSelfRef.tb_top__DOT__encap__DOT__out_ready));
    bufp->fullBit(oldp+429,(vlSelfRef.tb_top__DOT__encap__DOT__can_accept));
    bufp->fullBit(oldp+430,(vlSelfRef.tb_top__DOT__encap__DOT__fire_in));
    bufp->fullWData(oldp+431,(vlSelfRef.tb_top__DOT__encap__DOT__next_carry_data),224);
    bufp->fullIData(oldp+438,(vlSelfRef.tb_top__DOT__encap__DOT__next_carry_keep),28);
    bufp->fullBit(oldp+439,(vlSelfRef.tb_top__DOT__encap__DOT__need_tail));
}
