// *************************************************************************
//
// Copyright 2022 Xilinx, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// *************************************************************************
// Tier 1 — ERNIC1 5:2 AXI crossbar interconnect.
// Identical to axi_interconnect_to_sys_mem but for ERNIC instance 1.
// Reuses the same sys_mem_5to2_axi_crossbar IP with a different instance name.
//   M00 → sys_mem (QDMA bridge / host memory path)
//   M01 → dev_mem (DDR4 path via Tier 3 crossbar)
`timescale 1ns/1ps

module axi_interconnect_to_sys_mem_1 #(
  parameter C_AXI_DATA_WIDTH = 512,
  parameter C_AXI_ADDR_WIDTH = 64
) (
  input             s_axi_rdma_get_wqe_awid,
  input    [63 : 0] s_axi_rdma_get_wqe_awaddr,
  input     [3 : 0] s_axi_rdma_get_wqe_awqos,
  input     [7 : 0] s_axi_rdma_get_wqe_awlen,
  input     [2 : 0] s_axi_rdma_get_wqe_awsize,
  input     [1 : 0] s_axi_rdma_get_wqe_awburst,
  input     [3 : 0] s_axi_rdma_get_wqe_awcache,
  input     [2 : 0] s_axi_rdma_get_wqe_awprot,
  input             s_axi_rdma_get_wqe_awvalid,
  output            s_axi_rdma_get_wqe_awready,
  input   [511 : 0] s_axi_rdma_get_wqe_wdata,
  input    [63 : 0] s_axi_rdma_get_wqe_wstrb,
  input             s_axi_rdma_get_wqe_wlast,
  input             s_axi_rdma_get_wqe_wvalid,
  output            s_axi_rdma_get_wqe_wready,
  input             s_axi_rdma_get_wqe_awlock,
  output            s_axi_rdma_get_wqe_bid,
  output    [1 : 0] s_axi_rdma_get_wqe_bresp,
  output            s_axi_rdma_get_wqe_bvalid,
  input             s_axi_rdma_get_wqe_bready,
  input             s_axi_rdma_get_wqe_arid,
  input    [63 : 0] s_axi_rdma_get_wqe_araddr,
  input     [7 : 0] s_axi_rdma_get_wqe_arlen,
  input     [2 : 0] s_axi_rdma_get_wqe_arsize,
  input     [1 : 0] s_axi_rdma_get_wqe_arburst,
  input     [3 : 0] s_axi_rdma_get_wqe_arcache,
  input     [2 : 0] s_axi_rdma_get_wqe_arprot,
  input             s_axi_rdma_get_wqe_arvalid,
  output            s_axi_rdma_get_wqe_arready,
  output            s_axi_rdma_get_wqe_rid,
  output  [511 : 0] s_axi_rdma_get_wqe_rdata,
  output    [1 : 0] s_axi_rdma_get_wqe_rresp,
  output            s_axi_rdma_get_wqe_rlast,
  output            s_axi_rdma_get_wqe_rvalid,
  input             s_axi_rdma_get_wqe_rready,
  input             s_axi_rdma_get_wqe_arlock,
  input     [3 : 0] s_axi_rdma_get_wqe_arqos,

  input             s_axi_rdma_get_payload_awid,
  input    [63 : 0] s_axi_rdma_get_payload_awaddr,
  input     [3 : 0] s_axi_rdma_get_payload_awqos,
  input     [7 : 0] s_axi_rdma_get_payload_awlen,
  input     [2 : 0] s_axi_rdma_get_payload_awsize,
  input     [1 : 0] s_axi_rdma_get_payload_awburst,
  input     [3 : 0] s_axi_rdma_get_payload_awcache,
  input     [2 : 0] s_axi_rdma_get_payload_awprot,
  input             s_axi_rdma_get_payload_awvalid,
  output            s_axi_rdma_get_payload_awready,
  input   [511 : 0] s_axi_rdma_get_payload_wdata,
  input    [63 : 0] s_axi_rdma_get_payload_wstrb,
  input             s_axi_rdma_get_payload_wlast,
  input             s_axi_rdma_get_payload_wvalid,
  output            s_axi_rdma_get_payload_wready,
  input             s_axi_rdma_get_payload_awlock,
  output            s_axi_rdma_get_payload_bid,
  output    [1 : 0] s_axi_rdma_get_payload_bresp,
  output            s_axi_rdma_get_payload_bvalid,
  input             s_axi_rdma_get_payload_bready,
  input             s_axi_rdma_get_payload_arid,
  input    [63 : 0] s_axi_rdma_get_payload_araddr,
  input     [7 : 0] s_axi_rdma_get_payload_arlen,
  input     [2 : 0] s_axi_rdma_get_payload_arsize,
  input     [1 : 0] s_axi_rdma_get_payload_arburst,
  input     [3 : 0] s_axi_rdma_get_payload_arcache,
  input     [2 : 0] s_axi_rdma_get_payload_arprot,
  input             s_axi_rdma_get_payload_arvalid,
  output            s_axi_rdma_get_payload_arready,
  output            s_axi_rdma_get_payload_rid,
  output  [511 : 0] s_axi_rdma_get_payload_rdata,
  output    [1 : 0] s_axi_rdma_get_payload_rresp,
  output            s_axi_rdma_get_payload_rlast,
  output            s_axi_rdma_get_payload_rvalid,
  input             s_axi_rdma_get_payload_rready,
  input             s_axi_rdma_get_payload_arlock,
  input     [3 : 0] s_axi_rdma_get_payload_arqos,

  input             s_axi_rdma_completion_awid,
  input    [63 : 0] s_axi_rdma_completion_awaddr,
  input     [3 : 0] s_axi_rdma_completion_awqos,
  input     [7 : 0] s_axi_rdma_completion_awlen,
  input     [2 : 0] s_axi_rdma_completion_awsize,
  input     [1 : 0] s_axi_rdma_completion_awburst,
  input     [3 : 0] s_axi_rdma_completion_awcache,
  input     [2 : 0] s_axi_rdma_completion_awprot,
  input             s_axi_rdma_completion_awvalid,
  output            s_axi_rdma_completion_awready,
  input   [511 : 0] s_axi_rdma_completion_wdata,
  input    [63 : 0] s_axi_rdma_completion_wstrb,
  input             s_axi_rdma_completion_wlast,
  input             s_axi_rdma_completion_wvalid,
  output            s_axi_rdma_completion_wready,
  input             s_axi_rdma_completion_awlock,
  output            s_axi_rdma_completion_bid,
  output    [1 : 0] s_axi_rdma_completion_bresp,
  output            s_axi_rdma_completion_bvalid,
  input             s_axi_rdma_completion_bready,
  input             s_axi_rdma_completion_arid,
  input    [63 : 0] s_axi_rdma_completion_araddr,
  input     [7 : 0] s_axi_rdma_completion_arlen,
  input     [2 : 0] s_axi_rdma_completion_arsize,
  input     [1 : 0] s_axi_rdma_completion_arburst,
  input     [3 : 0] s_axi_rdma_completion_arcache,
  input     [2 : 0] s_axi_rdma_completion_arprot,
  input             s_axi_rdma_completion_arvalid,
  output            s_axi_rdma_completion_arready,
  output            s_axi_rdma_completion_rid,
  output  [511 : 0] s_axi_rdma_completion_rdata,
  output    [1 : 0] s_axi_rdma_completion_rresp,
  output            s_axi_rdma_completion_rlast,
  output            s_axi_rdma_completion_rvalid,
  input             s_axi_rdma_completion_rready,
  input             s_axi_rdma_completion_arlock,
  input     [3 : 0] s_axi_rdma_completion_arqos,

  input             s_axi_rdma_send_write_payload_awid,
  input    [63 : 0] s_axi_rdma_send_write_payload_awaddr,
  input     [3 : 0] s_axi_rdma_send_write_payload_awqos,
  input     [7 : 0] s_axi_rdma_send_write_payload_awlen,
  input     [2 : 0] s_axi_rdma_send_write_payload_awsize,
  input     [1 : 0] s_axi_rdma_send_write_payload_awburst,
  input     [3 : 0] s_axi_rdma_send_write_payload_awcache,
  input     [2 : 0] s_axi_rdma_send_write_payload_awprot,
  input             s_axi_rdma_send_write_payload_awvalid,
  output            s_axi_rdma_send_write_payload_awready,
  input   [511 : 0] s_axi_rdma_send_write_payload_wdata,
  input    [63 : 0] s_axi_rdma_send_write_payload_wstrb,
  input             s_axi_rdma_send_write_payload_wlast,
  input             s_axi_rdma_send_write_payload_wvalid,
  output            s_axi_rdma_send_write_payload_wready,
  input             s_axi_rdma_send_write_payload_awlock,
  output            s_axi_rdma_send_write_payload_bid,
  output    [1 : 0] s_axi_rdma_send_write_payload_bresp,
  output            s_axi_rdma_send_write_payload_bvalid,
  input             s_axi_rdma_send_write_payload_bready,
  input             s_axi_rdma_send_write_payload_arid,
  input    [63 : 0] s_axi_rdma_send_write_payload_araddr,
  input     [7 : 0] s_axi_rdma_send_write_payload_arlen,
  input     [2 : 0] s_axi_rdma_send_write_payload_arsize,
  input     [1 : 0] s_axi_rdma_send_write_payload_arburst,
  input     [3 : 0] s_axi_rdma_send_write_payload_arcache,
  input     [2 : 0] s_axi_rdma_send_write_payload_arprot,
  input             s_axi_rdma_send_write_payload_arvalid,
  output            s_axi_rdma_send_write_payload_arready,
  output            s_axi_rdma_send_write_payload_rid,
  output  [511 : 0] s_axi_rdma_send_write_payload_rdata,
  output    [1 : 0] s_axi_rdma_send_write_payload_rresp,
  output            s_axi_rdma_send_write_payload_rlast,
  output            s_axi_rdma_send_write_payload_rvalid,
  input             s_axi_rdma_send_write_payload_rready,
  input             s_axi_rdma_send_write_payload_arlock,
  input     [3 : 0] s_axi_rdma_send_write_payload_arqos,

  input             s_axi_rdma_rsp_payload_awid,
  input    [63 : 0] s_axi_rdma_rsp_payload_awaddr,
  input     [3 : 0] s_axi_rdma_rsp_payload_awqos,
  input     [7 : 0] s_axi_rdma_rsp_payload_awlen,
  input     [2 : 0] s_axi_rdma_rsp_payload_awsize,
  input     [1 : 0] s_axi_rdma_rsp_payload_awburst,
  input     [3 : 0] s_axi_rdma_rsp_payload_awcache,
  input     [2 : 0] s_axi_rdma_rsp_payload_awprot,
  input             s_axi_rdma_rsp_payload_awvalid,
  output            s_axi_rdma_rsp_payload_awready,
  input   [511 : 0] s_axi_rdma_rsp_payload_wdata,
  input    [63 : 0] s_axi_rdma_rsp_payload_wstrb,
  input             s_axi_rdma_rsp_payload_wlast,
  input             s_axi_rdma_rsp_payload_wvalid,
  output            s_axi_rdma_rsp_payload_wready,
  input             s_axi_rdma_rsp_payload_awlock,
  output            s_axi_rdma_rsp_payload_bid,
  output    [1 : 0] s_axi_rdma_rsp_payload_bresp,
  output            s_axi_rdma_rsp_payload_bvalid,
  input             s_axi_rdma_rsp_payload_bready,
  input             s_axi_rdma_rsp_payload_arid,
  input    [63 : 0] s_axi_rdma_rsp_payload_araddr,
  input     [7 : 0] s_axi_rdma_rsp_payload_arlen,
  input     [2 : 0] s_axi_rdma_rsp_payload_arsize,
  input     [1 : 0] s_axi_rdma_rsp_payload_arburst,
  input     [3 : 0] s_axi_rdma_rsp_payload_arcache,
  input     [2 : 0] s_axi_rdma_rsp_payload_arprot,
  input             s_axi_rdma_rsp_payload_arvalid,
  output            s_axi_rdma_rsp_payload_arready,
  output            s_axi_rdma_rsp_payload_rid,
  output  [511 : 0] s_axi_rdma_rsp_payload_rdata,
  output    [1 : 0] s_axi_rdma_rsp_payload_rresp,
  output            s_axi_rdma_rsp_payload_rlast,
  output            s_axi_rdma_rsp_payload_rvalid,
  input             s_axi_rdma_rsp_payload_rready,
  input             s_axi_rdma_rsp_payload_arlock,
  input     [3 : 0] s_axi_rdma_rsp_payload_arqos,

  // M00: sys_mem output (to QDMA bridge / host memory)
  output      [2:0] m_axi_sys_mem_awid,
  output     [63:0] m_axi_sys_mem_awaddr,
  output      [7:0] m_axi_sys_mem_awlen,
  output      [2:0] m_axi_sys_mem_awsize,
  output      [1:0] m_axi_sys_mem_awburst,
  output            m_axi_sys_mem_awlock,
  output      [3:0] m_axi_sys_mem_awqos,
  output      [3:0] m_axi_sys_mem_awregion,
  output      [3:0] m_axi_sys_mem_awcache,
  output      [2:0] m_axi_sys_mem_awprot,
  output            m_axi_sys_mem_awvalid,
  input             m_axi_sys_mem_awready,
  output    [511:0] m_axi_sys_mem_wdata,
  output     [63:0] m_axi_sys_mem_wstrb,
  output            m_axi_sys_mem_wlast,
  output            m_axi_sys_mem_wvalid,
  input             m_axi_sys_mem_wready,
  input       [2:0] m_axi_sys_mem_bid,
  input       [1:0] m_axi_sys_mem_bresp,
  input             m_axi_sys_mem_bvalid,
  output            m_axi_sys_mem_bready,
  output      [2:0] m_axi_sys_mem_arid,
  output     [63:0] m_axi_sys_mem_araddr,
  output      [7:0] m_axi_sys_mem_arlen,
  output      [2:0] m_axi_sys_mem_arsize,
  output      [1:0] m_axi_sys_mem_arburst,
  output            m_axi_sys_mem_arlock,
  output      [3:0] m_axi_sys_mem_arqos,
  output      [3:0] m_axi_sys_mem_arregion,
  output      [3:0] m_axi_sys_mem_arcache,
  output      [2:0] m_axi_sys_mem_arprot,
  output            m_axi_sys_mem_arvalid,
  input             m_axi_sys_mem_arready,
  input       [2:0] m_axi_sys_mem_rid,
  input     [511:0] m_axi_sys_mem_rdata,
  input       [1:0] m_axi_sys_mem_rresp,
  input             m_axi_sys_mem_rlast,
  input             m_axi_sys_mem_rvalid,
  output            m_axi_sys_mem_rready,

  // M01: dev_mem output (to Tier 3 dev_mem crossbar)
  output      [2:0] m_axi_sys_to_dev_crossbar_awid,
  output     [63:0] m_axi_sys_to_dev_crossbar_awaddr,
  output      [7:0] m_axi_sys_to_dev_crossbar_awlen,
  output      [2:0] m_axi_sys_to_dev_crossbar_awsize,
  output      [1:0] m_axi_sys_to_dev_crossbar_awburst,
  output            m_axi_sys_to_dev_crossbar_awlock,
  output      [3:0] m_axi_sys_to_dev_crossbar_awqos,
  output      [3:0] m_axi_sys_to_dev_crossbar_awregion,
  output      [3:0] m_axi_sys_to_dev_crossbar_awcache,
  output      [2:0] m_axi_sys_to_dev_crossbar_awprot,
  output            m_axi_sys_to_dev_crossbar_awvalid,
  input             m_axi_sys_to_dev_crossbar_awready,
  output    [511:0] m_axi_sys_to_dev_crossbar_wdata,
  output     [63:0] m_axi_sys_to_dev_crossbar_wstrb,
  output            m_axi_sys_to_dev_crossbar_wlast,
  output            m_axi_sys_to_dev_crossbar_wvalid,
  input             m_axi_sys_to_dev_crossbar_wready,
  input       [2:0] m_axi_sys_to_dev_crossbar_bid,
  input       [1:0] m_axi_sys_to_dev_crossbar_bresp,
  input             m_axi_sys_to_dev_crossbar_bvalid,
  output            m_axi_sys_to_dev_crossbar_bready,
  output      [2:0] m_axi_sys_to_dev_crossbar_arid,
  output     [63:0] m_axi_sys_to_dev_crossbar_araddr,
  output      [7:0] m_axi_sys_to_dev_crossbar_arlen,
  output      [2:0] m_axi_sys_to_dev_crossbar_arsize,
  output      [1:0] m_axi_sys_to_dev_crossbar_arburst,
  output            m_axi_sys_to_dev_crossbar_arlock,
  output      [3:0] m_axi_sys_to_dev_crossbar_arqos,
  output      [3:0] m_axi_sys_to_dev_crossbar_arregion,
  output      [3:0] m_axi_sys_to_dev_crossbar_arcache,
  output      [2:0] m_axi_sys_to_dev_crossbar_arprot,
  output            m_axi_sys_to_dev_crossbar_arvalid,
  input             m_axi_sys_to_dev_crossbar_arready,
  input       [2:0] m_axi_sys_to_dev_crossbar_rid,
  input     [511:0] m_axi_sys_to_dev_crossbar_rdata,
  input       [1:0] m_axi_sys_to_dev_crossbar_rresp,
  input             m_axi_sys_to_dev_crossbar_rlast,
  input             m_axi_sys_to_dev_crossbar_rvalid,
  output            m_axi_sys_to_dev_crossbar_rready,

  input axis_aclk,
  input axis_arestn
);

// Instantiate ERNIC0's interconnect as a sub-module. The _1 wrapper exists
// so that the parent can distinguish the two instances by module name.
// Both instantiate the same sys_mem_5to2_axi_crossbar Vivado IP.

axi_interconnect_to_sys_mem #(
  .C_AXI_DATA_WIDTH (C_AXI_DATA_WIDTH),
  .C_AXI_ADDR_WIDTH (C_AXI_ADDR_WIDTH)
) axi_interconnect_to_sys_mem_1_inst (
  .s_axi_rdma_get_wqe_awid                (s_axi_rdma_get_wqe_awid),
  .s_axi_rdma_get_wqe_awaddr              (s_axi_rdma_get_wqe_awaddr),
  .s_axi_rdma_get_wqe_awqos               (s_axi_rdma_get_wqe_awqos),
  .s_axi_rdma_get_wqe_awlen               (s_axi_rdma_get_wqe_awlen),
  .s_axi_rdma_get_wqe_awsize              (s_axi_rdma_get_wqe_awsize),
  .s_axi_rdma_get_wqe_awburst             (s_axi_rdma_get_wqe_awburst),
  .s_axi_rdma_get_wqe_awcache             (s_axi_rdma_get_wqe_awcache),
  .s_axi_rdma_get_wqe_awprot              (s_axi_rdma_get_wqe_awprot),
  .s_axi_rdma_get_wqe_awvalid             (s_axi_rdma_get_wqe_awvalid),
  .s_axi_rdma_get_wqe_awready             (s_axi_rdma_get_wqe_awready),
  .s_axi_rdma_get_wqe_wdata               (s_axi_rdma_get_wqe_wdata),
  .s_axi_rdma_get_wqe_wstrb               (s_axi_rdma_get_wqe_wstrb),
  .s_axi_rdma_get_wqe_wlast               (s_axi_rdma_get_wqe_wlast),
  .s_axi_rdma_get_wqe_wvalid              (s_axi_rdma_get_wqe_wvalid),
  .s_axi_rdma_get_wqe_wready              (s_axi_rdma_get_wqe_wready),
  .s_axi_rdma_get_wqe_awlock              (s_axi_rdma_get_wqe_awlock),
  .s_axi_rdma_get_wqe_bid                 (s_axi_rdma_get_wqe_bid),
  .s_axi_rdma_get_wqe_bresp               (s_axi_rdma_get_wqe_bresp),
  .s_axi_rdma_get_wqe_bvalid              (s_axi_rdma_get_wqe_bvalid),
  .s_axi_rdma_get_wqe_bready              (s_axi_rdma_get_wqe_bready),
  .s_axi_rdma_get_wqe_arid                (s_axi_rdma_get_wqe_arid),
  .s_axi_rdma_get_wqe_araddr              (s_axi_rdma_get_wqe_araddr),
  .s_axi_rdma_get_wqe_arlen               (s_axi_rdma_get_wqe_arlen),
  .s_axi_rdma_get_wqe_arsize              (s_axi_rdma_get_wqe_arsize),
  .s_axi_rdma_get_wqe_arburst             (s_axi_rdma_get_wqe_arburst),
  .s_axi_rdma_get_wqe_arcache             (s_axi_rdma_get_wqe_arcache),
  .s_axi_rdma_get_wqe_arprot              (s_axi_rdma_get_wqe_arprot),
  .s_axi_rdma_get_wqe_arvalid             (s_axi_rdma_get_wqe_arvalid),
  .s_axi_rdma_get_wqe_arready             (s_axi_rdma_get_wqe_arready),
  .s_axi_rdma_get_wqe_rid                 (s_axi_rdma_get_wqe_rid),
  .s_axi_rdma_get_wqe_rdata               (s_axi_rdma_get_wqe_rdata),
  .s_axi_rdma_get_wqe_rresp               (s_axi_rdma_get_wqe_rresp),
  .s_axi_rdma_get_wqe_rlast               (s_axi_rdma_get_wqe_rlast),
  .s_axi_rdma_get_wqe_rvalid              (s_axi_rdma_get_wqe_rvalid),
  .s_axi_rdma_get_wqe_rready              (s_axi_rdma_get_wqe_rready),
  .s_axi_rdma_get_wqe_arlock              (s_axi_rdma_get_wqe_arlock),
  .s_axi_rdma_get_wqe_arqos               (s_axi_rdma_get_wqe_arqos),

  .s_axi_rdma_get_payload_awid             (s_axi_rdma_get_payload_awid),
  .s_axi_rdma_get_payload_awaddr           (s_axi_rdma_get_payload_awaddr),
  .s_axi_rdma_get_payload_awqos            (s_axi_rdma_get_payload_awqos),
  .s_axi_rdma_get_payload_awlen            (s_axi_rdma_get_payload_awlen),
  .s_axi_rdma_get_payload_awsize           (s_axi_rdma_get_payload_awsize),
  .s_axi_rdma_get_payload_awburst          (s_axi_rdma_get_payload_awburst),
  .s_axi_rdma_get_payload_awcache          (s_axi_rdma_get_payload_awcache),
  .s_axi_rdma_get_payload_awprot           (s_axi_rdma_get_payload_awprot),
  .s_axi_rdma_get_payload_awvalid          (s_axi_rdma_get_payload_awvalid),
  .s_axi_rdma_get_payload_awready          (s_axi_rdma_get_payload_awready),
  .s_axi_rdma_get_payload_wdata            (s_axi_rdma_get_payload_wdata),
  .s_axi_rdma_get_payload_wstrb            (s_axi_rdma_get_payload_wstrb),
  .s_axi_rdma_get_payload_wlast            (s_axi_rdma_get_payload_wlast),
  .s_axi_rdma_get_payload_wvalid           (s_axi_rdma_get_payload_wvalid),
  .s_axi_rdma_get_payload_wready           (s_axi_rdma_get_payload_wready),
  .s_axi_rdma_get_payload_awlock           (s_axi_rdma_get_payload_awlock),
  .s_axi_rdma_get_payload_bid              (s_axi_rdma_get_payload_bid),
  .s_axi_rdma_get_payload_bresp            (s_axi_rdma_get_payload_bresp),
  .s_axi_rdma_get_payload_bvalid           (s_axi_rdma_get_payload_bvalid),
  .s_axi_rdma_get_payload_bready           (s_axi_rdma_get_payload_bready),
  .s_axi_rdma_get_payload_arid             (s_axi_rdma_get_payload_arid),
  .s_axi_rdma_get_payload_araddr           (s_axi_rdma_get_payload_araddr),
  .s_axi_rdma_get_payload_arlen            (s_axi_rdma_get_payload_arlen),
  .s_axi_rdma_get_payload_arsize           (s_axi_rdma_get_payload_arsize),
  .s_axi_rdma_get_payload_arburst          (s_axi_rdma_get_payload_arburst),
  .s_axi_rdma_get_payload_arcache          (s_axi_rdma_get_payload_arcache),
  .s_axi_rdma_get_payload_arprot           (s_axi_rdma_get_payload_arprot),
  .s_axi_rdma_get_payload_arvalid          (s_axi_rdma_get_payload_arvalid),
  .s_axi_rdma_get_payload_arready          (s_axi_rdma_get_payload_arready),
  .s_axi_rdma_get_payload_rid              (s_axi_rdma_get_payload_rid),
  .s_axi_rdma_get_payload_rdata            (s_axi_rdma_get_payload_rdata),
  .s_axi_rdma_get_payload_rresp            (s_axi_rdma_get_payload_rresp),
  .s_axi_rdma_get_payload_rlast            (s_axi_rdma_get_payload_rlast),
  .s_axi_rdma_get_payload_rvalid           (s_axi_rdma_get_payload_rvalid),
  .s_axi_rdma_get_payload_rready           (s_axi_rdma_get_payload_rready),
  .s_axi_rdma_get_payload_arlock           (s_axi_rdma_get_payload_arlock),
  .s_axi_rdma_get_payload_arqos            (s_axi_rdma_get_payload_arqos),

  .s_axi_rdma_completion_awid              (s_axi_rdma_completion_awid),
  .s_axi_rdma_completion_awaddr            (s_axi_rdma_completion_awaddr),
  .s_axi_rdma_completion_awqos             (s_axi_rdma_completion_awqos),
  .s_axi_rdma_completion_awlen             (s_axi_rdma_completion_awlen),
  .s_axi_rdma_completion_awsize            (s_axi_rdma_completion_awsize),
  .s_axi_rdma_completion_awburst           (s_axi_rdma_completion_awburst),
  .s_axi_rdma_completion_awcache           (s_axi_rdma_completion_awcache),
  .s_axi_rdma_completion_awprot            (s_axi_rdma_completion_awprot),
  .s_axi_rdma_completion_awvalid           (s_axi_rdma_completion_awvalid),
  .s_axi_rdma_completion_awready           (s_axi_rdma_completion_awready),
  .s_axi_rdma_completion_wdata             (s_axi_rdma_completion_wdata),
  .s_axi_rdma_completion_wstrb             (s_axi_rdma_completion_wstrb),
  .s_axi_rdma_completion_wlast             (s_axi_rdma_completion_wlast),
  .s_axi_rdma_completion_wvalid            (s_axi_rdma_completion_wvalid),
  .s_axi_rdma_completion_wready            (s_axi_rdma_completion_wready),
  .s_axi_rdma_completion_awlock            (s_axi_rdma_completion_awlock),
  .s_axi_rdma_completion_bid               (s_axi_rdma_completion_bid),
  .s_axi_rdma_completion_bresp             (s_axi_rdma_completion_bresp),
  .s_axi_rdma_completion_bvalid            (s_axi_rdma_completion_bvalid),
  .s_axi_rdma_completion_bready            (s_axi_rdma_completion_bready),
  .s_axi_rdma_completion_arid              (s_axi_rdma_completion_arid),
  .s_axi_rdma_completion_araddr            (s_axi_rdma_completion_araddr),
  .s_axi_rdma_completion_arlen             (s_axi_rdma_completion_arlen),
  .s_axi_rdma_completion_arsize            (s_axi_rdma_completion_arsize),
  .s_axi_rdma_completion_arburst           (s_axi_rdma_completion_arburst),
  .s_axi_rdma_completion_arcache           (s_axi_rdma_completion_arcache),
  .s_axi_rdma_completion_arprot            (s_axi_rdma_completion_arprot),
  .s_axi_rdma_completion_arvalid           (s_axi_rdma_completion_arvalid),
  .s_axi_rdma_completion_arready           (s_axi_rdma_completion_arready),
  .s_axi_rdma_completion_rid               (s_axi_rdma_completion_rid),
  .s_axi_rdma_completion_rdata             (s_axi_rdma_completion_rdata),
  .s_axi_rdma_completion_rresp             (s_axi_rdma_completion_rresp),
  .s_axi_rdma_completion_rlast             (s_axi_rdma_completion_rlast),
  .s_axi_rdma_completion_rvalid            (s_axi_rdma_completion_rvalid),
  .s_axi_rdma_completion_rready            (s_axi_rdma_completion_rready),
  .s_axi_rdma_completion_arlock            (s_axi_rdma_completion_arlock),
  .s_axi_rdma_completion_arqos             (s_axi_rdma_completion_arqos),

  .s_axi_rdma_send_write_payload_awid      (s_axi_rdma_send_write_payload_awid),
  .s_axi_rdma_send_write_payload_awaddr    (s_axi_rdma_send_write_payload_awaddr),
  .s_axi_rdma_send_write_payload_awqos     (s_axi_rdma_send_write_payload_awqos),
  .s_axi_rdma_send_write_payload_awlen     (s_axi_rdma_send_write_payload_awlen),
  .s_axi_rdma_send_write_payload_awsize    (s_axi_rdma_send_write_payload_awsize),
  .s_axi_rdma_send_write_payload_awburst   (s_axi_rdma_send_write_payload_awburst),
  .s_axi_rdma_send_write_payload_awcache   (s_axi_rdma_send_write_payload_awcache),
  .s_axi_rdma_send_write_payload_awprot    (s_axi_rdma_send_write_payload_awprot),
  .s_axi_rdma_send_write_payload_awvalid   (s_axi_rdma_send_write_payload_awvalid),
  .s_axi_rdma_send_write_payload_awready   (s_axi_rdma_send_write_payload_awready),
  .s_axi_rdma_send_write_payload_wdata     (s_axi_rdma_send_write_payload_wdata),
  .s_axi_rdma_send_write_payload_wstrb     (s_axi_rdma_send_write_payload_wstrb),
  .s_axi_rdma_send_write_payload_wlast     (s_axi_rdma_send_write_payload_wlast),
  .s_axi_rdma_send_write_payload_wvalid    (s_axi_rdma_send_write_payload_wvalid),
  .s_axi_rdma_send_write_payload_wready    (s_axi_rdma_send_write_payload_wready),
  .s_axi_rdma_send_write_payload_awlock    (s_axi_rdma_send_write_payload_awlock),
  .s_axi_rdma_send_write_payload_bid       (s_axi_rdma_send_write_payload_bid),
  .s_axi_rdma_send_write_payload_bresp     (s_axi_rdma_send_write_payload_bresp),
  .s_axi_rdma_send_write_payload_bvalid    (s_axi_rdma_send_write_payload_bvalid),
  .s_axi_rdma_send_write_payload_bready    (s_axi_rdma_send_write_payload_bready),
  .s_axi_rdma_send_write_payload_arid      (s_axi_rdma_send_write_payload_arid),
  .s_axi_rdma_send_write_payload_araddr    (s_axi_rdma_send_write_payload_araddr),
  .s_axi_rdma_send_write_payload_arlen     (s_axi_rdma_send_write_payload_arlen),
  .s_axi_rdma_send_write_payload_arsize    (s_axi_rdma_send_write_payload_arsize),
  .s_axi_rdma_send_write_payload_arburst   (s_axi_rdma_send_write_payload_arburst),
  .s_axi_rdma_send_write_payload_arcache   (s_axi_rdma_send_write_payload_arcache),
  .s_axi_rdma_send_write_payload_arprot    (s_axi_rdma_send_write_payload_arprot),
  .s_axi_rdma_send_write_payload_arvalid   (s_axi_rdma_send_write_payload_arvalid),
  .s_axi_rdma_send_write_payload_arready   (s_axi_rdma_send_write_payload_arready),
  .s_axi_rdma_send_write_payload_rid       (s_axi_rdma_send_write_payload_rid),
  .s_axi_rdma_send_write_payload_rdata     (s_axi_rdma_send_write_payload_rdata),
  .s_axi_rdma_send_write_payload_rresp     (s_axi_rdma_send_write_payload_rresp),
  .s_axi_rdma_send_write_payload_rlast     (s_axi_rdma_send_write_payload_rlast),
  .s_axi_rdma_send_write_payload_rvalid    (s_axi_rdma_send_write_payload_rvalid),
  .s_axi_rdma_send_write_payload_rready    (s_axi_rdma_send_write_payload_rready),
  .s_axi_rdma_send_write_payload_arlock    (s_axi_rdma_send_write_payload_arlock),
  .s_axi_rdma_send_write_payload_arqos     (s_axi_rdma_send_write_payload_arqos),

  .s_axi_rdma_rsp_payload_awid             (s_axi_rdma_rsp_payload_awid),
  .s_axi_rdma_rsp_payload_awaddr           (s_axi_rdma_rsp_payload_awaddr),
  .s_axi_rdma_rsp_payload_awqos            (s_axi_rdma_rsp_payload_awqos),
  .s_axi_rdma_rsp_payload_awlen            (s_axi_rdma_rsp_payload_awlen),
  .s_axi_rdma_rsp_payload_awsize           (s_axi_rdma_rsp_payload_awsize),
  .s_axi_rdma_rsp_payload_awburst          (s_axi_rdma_rsp_payload_awburst),
  .s_axi_rdma_rsp_payload_awcache          (s_axi_rdma_rsp_payload_awcache),
  .s_axi_rdma_rsp_payload_awprot           (s_axi_rdma_rsp_payload_awprot),
  .s_axi_rdma_rsp_payload_awvalid          (s_axi_rdma_rsp_payload_awvalid),
  .s_axi_rdma_rsp_payload_awready          (s_axi_rdma_rsp_payload_awready),
  .s_axi_rdma_rsp_payload_wdata            (s_axi_rdma_rsp_payload_wdata),
  .s_axi_rdma_rsp_payload_wstrb            (s_axi_rdma_rsp_payload_wstrb),
  .s_axi_rdma_rsp_payload_wlast            (s_axi_rdma_rsp_payload_wlast),
  .s_axi_rdma_rsp_payload_wvalid           (s_axi_rdma_rsp_payload_wvalid),
  .s_axi_rdma_rsp_payload_wready           (s_axi_rdma_rsp_payload_wready),
  .s_axi_rdma_rsp_payload_awlock           (s_axi_rdma_rsp_payload_awlock),
  .s_axi_rdma_rsp_payload_bid              (s_axi_rdma_rsp_payload_bid),
  .s_axi_rdma_rsp_payload_bresp            (s_axi_rdma_rsp_payload_bresp),
  .s_axi_rdma_rsp_payload_bvalid           (s_axi_rdma_rsp_payload_bvalid),
  .s_axi_rdma_rsp_payload_bready           (s_axi_rdma_rsp_payload_bready),
  .s_axi_rdma_rsp_payload_arid             (s_axi_rdma_rsp_payload_arid),
  .s_axi_rdma_rsp_payload_araddr           (s_axi_rdma_rsp_payload_araddr),
  .s_axi_rdma_rsp_payload_arlen            (s_axi_rdma_rsp_payload_arlen),
  .s_axi_rdma_rsp_payload_arsize           (s_axi_rdma_rsp_payload_arsize),
  .s_axi_rdma_rsp_payload_arburst          (s_axi_rdma_rsp_payload_arburst),
  .s_axi_rdma_rsp_payload_arcache          (s_axi_rdma_rsp_payload_arcache),
  .s_axi_rdma_rsp_payload_arprot           (s_axi_rdma_rsp_payload_arprot),
  .s_axi_rdma_rsp_payload_arvalid          (s_axi_rdma_rsp_payload_arvalid),
  .s_axi_rdma_rsp_payload_arready          (s_axi_rdma_rsp_payload_arready),
  .s_axi_rdma_rsp_payload_rid              (s_axi_rdma_rsp_payload_rid),
  .s_axi_rdma_rsp_payload_rdata            (s_axi_rdma_rsp_payload_rdata),
  .s_axi_rdma_rsp_payload_rresp            (s_axi_rdma_rsp_payload_rresp),
  .s_axi_rdma_rsp_payload_rlast            (s_axi_rdma_rsp_payload_rlast),
  .s_axi_rdma_rsp_payload_rvalid           (s_axi_rdma_rsp_payload_rvalid),
  .s_axi_rdma_rsp_payload_rready           (s_axi_rdma_rsp_payload_rready),
  .s_axi_rdma_rsp_payload_arlock           (s_axi_rdma_rsp_payload_arlock),
  .s_axi_rdma_rsp_payload_arqos            (s_axi_rdma_rsp_payload_arqos),

  .m_axi_sys_mem_awid                      (m_axi_sys_mem_awid),
  .m_axi_sys_mem_awaddr                    (m_axi_sys_mem_awaddr),
  .m_axi_sys_mem_awlen                     (m_axi_sys_mem_awlen),
  .m_axi_sys_mem_awsize                    (m_axi_sys_mem_awsize),
  .m_axi_sys_mem_awburst                   (m_axi_sys_mem_awburst),
  .m_axi_sys_mem_awlock                    (m_axi_sys_mem_awlock),
  .m_axi_sys_mem_awqos                     (m_axi_sys_mem_awqos),
  .m_axi_sys_mem_awregion                  (m_axi_sys_mem_awregion),
  .m_axi_sys_mem_awcache                   (m_axi_sys_mem_awcache),
  .m_axi_sys_mem_awprot                    (m_axi_sys_mem_awprot),
  .m_axi_sys_mem_awvalid                   (m_axi_sys_mem_awvalid),
  .m_axi_sys_mem_awready                   (m_axi_sys_mem_awready),
  .m_axi_sys_mem_wdata                     (m_axi_sys_mem_wdata),
  .m_axi_sys_mem_wstrb                     (m_axi_sys_mem_wstrb),
  .m_axi_sys_mem_wlast                     (m_axi_sys_mem_wlast),
  .m_axi_sys_mem_wvalid                    (m_axi_sys_mem_wvalid),
  .m_axi_sys_mem_wready                    (m_axi_sys_mem_wready),
  .m_axi_sys_mem_bid                       (m_axi_sys_mem_bid),
  .m_axi_sys_mem_bresp                     (m_axi_sys_mem_bresp),
  .m_axi_sys_mem_bvalid                    (m_axi_sys_mem_bvalid),
  .m_axi_sys_mem_bready                    (m_axi_sys_mem_bready),
  .m_axi_sys_mem_arid                      (m_axi_sys_mem_arid),
  .m_axi_sys_mem_araddr                    (m_axi_sys_mem_araddr),
  .m_axi_sys_mem_arlen                     (m_axi_sys_mem_arlen),
  .m_axi_sys_mem_arsize                    (m_axi_sys_mem_arsize),
  .m_axi_sys_mem_arburst                   (m_axi_sys_mem_arburst),
  .m_axi_sys_mem_arlock                    (m_axi_sys_mem_arlock),
  .m_axi_sys_mem_arqos                     (m_axi_sys_mem_arqos),
  .m_axi_sys_mem_arregion                  (m_axi_sys_mem_arregion),
  .m_axi_sys_mem_arcache                   (m_axi_sys_mem_arcache),
  .m_axi_sys_mem_arprot                    (m_axi_sys_mem_arprot),
  .m_axi_sys_mem_arvalid                   (m_axi_sys_mem_arvalid),
  .m_axi_sys_mem_arready                   (m_axi_sys_mem_arready),
  .m_axi_sys_mem_rid                       (m_axi_sys_mem_rid),
  .m_axi_sys_mem_rdata                     (m_axi_sys_mem_rdata),
  .m_axi_sys_mem_rresp                     (m_axi_sys_mem_rresp),
  .m_axi_sys_mem_rlast                     (m_axi_sys_mem_rlast),
  .m_axi_sys_mem_rvalid                    (m_axi_sys_mem_rvalid),
  .m_axi_sys_mem_rready                    (m_axi_sys_mem_rready),

  .m_axi_sys_to_dev_crossbar_awid          (m_axi_sys_to_dev_crossbar_awid),
  .m_axi_sys_to_dev_crossbar_awaddr        (m_axi_sys_to_dev_crossbar_awaddr),
  .m_axi_sys_to_dev_crossbar_awlen         (m_axi_sys_to_dev_crossbar_awlen),
  .m_axi_sys_to_dev_crossbar_awsize        (m_axi_sys_to_dev_crossbar_awsize),
  .m_axi_sys_to_dev_crossbar_awburst       (m_axi_sys_to_dev_crossbar_awburst),
  .m_axi_sys_to_dev_crossbar_awlock        (m_axi_sys_to_dev_crossbar_awlock),
  .m_axi_sys_to_dev_crossbar_awqos         (m_axi_sys_to_dev_crossbar_awqos),
  .m_axi_sys_to_dev_crossbar_awregion      (m_axi_sys_to_dev_crossbar_awregion),
  .m_axi_sys_to_dev_crossbar_awcache       (m_axi_sys_to_dev_crossbar_awcache),
  .m_axi_sys_to_dev_crossbar_awprot        (m_axi_sys_to_dev_crossbar_awprot),
  .m_axi_sys_to_dev_crossbar_awvalid       (m_axi_sys_to_dev_crossbar_awvalid),
  .m_axi_sys_to_dev_crossbar_awready       (m_axi_sys_to_dev_crossbar_awready),
  .m_axi_sys_to_dev_crossbar_wdata         (m_axi_sys_to_dev_crossbar_wdata),
  .m_axi_sys_to_dev_crossbar_wstrb         (m_axi_sys_to_dev_crossbar_wstrb),
  .m_axi_sys_to_dev_crossbar_wlast         (m_axi_sys_to_dev_crossbar_wlast),
  .m_axi_sys_to_dev_crossbar_wvalid        (m_axi_sys_to_dev_crossbar_wvalid),
  .m_axi_sys_to_dev_crossbar_wready        (m_axi_sys_to_dev_crossbar_wready),
  .m_axi_sys_to_dev_crossbar_bid           (m_axi_sys_to_dev_crossbar_bid),
  .m_axi_sys_to_dev_crossbar_bresp         (m_axi_sys_to_dev_crossbar_bresp),
  .m_axi_sys_to_dev_crossbar_bvalid        (m_axi_sys_to_dev_crossbar_bvalid),
  .m_axi_sys_to_dev_crossbar_bready        (m_axi_sys_to_dev_crossbar_bready),
  .m_axi_sys_to_dev_crossbar_arid          (m_axi_sys_to_dev_crossbar_arid),
  .m_axi_sys_to_dev_crossbar_araddr        (m_axi_sys_to_dev_crossbar_araddr),
  .m_axi_sys_to_dev_crossbar_arlen         (m_axi_sys_to_dev_crossbar_arlen),
  .m_axi_sys_to_dev_crossbar_arsize        (m_axi_sys_to_dev_crossbar_arsize),
  .m_axi_sys_to_dev_crossbar_arburst       (m_axi_sys_to_dev_crossbar_arburst),
  .m_axi_sys_to_dev_crossbar_arlock        (m_axi_sys_to_dev_crossbar_arlock),
  .m_axi_sys_to_dev_crossbar_arqos         (m_axi_sys_to_dev_crossbar_arqos),
  .m_axi_sys_to_dev_crossbar_arregion      (m_axi_sys_to_dev_crossbar_arregion),
  .m_axi_sys_to_dev_crossbar_arcache       (m_axi_sys_to_dev_crossbar_arcache),
  .m_axi_sys_to_dev_crossbar_arprot        (m_axi_sys_to_dev_crossbar_arprot),
  .m_axi_sys_to_dev_crossbar_arvalid       (m_axi_sys_to_dev_crossbar_arvalid),
  .m_axi_sys_to_dev_crossbar_arready       (m_axi_sys_to_dev_crossbar_arready),
  .m_axi_sys_to_dev_crossbar_rid           (m_axi_sys_to_dev_crossbar_rid),
  .m_axi_sys_to_dev_crossbar_rdata         (m_axi_sys_to_dev_crossbar_rdata),
  .m_axi_sys_to_dev_crossbar_rresp         (m_axi_sys_to_dev_crossbar_rresp),
  .m_axi_sys_to_dev_crossbar_rlast         (m_axi_sys_to_dev_crossbar_rlast),
  .m_axi_sys_to_dev_crossbar_rvalid        (m_axi_sys_to_dev_crossbar_rvalid),
  .m_axi_sys_to_dev_crossbar_rready        (m_axi_sys_to_dev_crossbar_rready),

  .axis_aclk   (axis_aclk),
  .axis_arestn (axis_arestn)
);

endmodule: axi_interconnect_to_sys_mem_1
