# *************************************************************************
#
# Copyright 2024 AMD, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# *************************************************************************
# PTP subsystem uses Corundum Verilog modules (ptp_clock, ptp_clock_cdc)
# which are pure RTL with no generated IP dependencies.  The TX timestamp
# async FIFOs use xpm_fifo_async which is a built-in XPM primitive and
# does not require IP generation.  The AXI-Lite clock converter IP is
# already generated by the utility subsystem.
set ips {}
